[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyCn5CJHBqIG_EkuNKW8ctMonx_O4j9xLvo"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "boredgamer-ad280.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "boredgamer-ad280"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "boredgamer-ad280.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "867192671855"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:867192671855:web:39152e848d742cafa5479a"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
