[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_FIREBASE_API_KEY = ""
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = ""
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = ""
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = ""
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = ""
  NEXT_PUBLIC_FIREBASE_APP_ID = ""
  FIREBASE_ADMIN_PROJECT_ID = ""
  FIREBASE_ADMIN_CLIENT_EMAIL = ""
  FIREBASE_ADMIN_PRIVATE_KEY = ""
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"
